language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - hexo clean
  - hexo generate
  - echo "https://hhhdddwww%40163.com:"$GIT_PWD"@github.com" >> ~/.git-credentials
  - git config --global credential.helper store
  - hexo deploy